describe('Login Page', () => {
  it('Input Invalid Username and Password', () => {
    cy.visit('http://localhost:4200/login')
    cy.url().should('include', '/login')
    cy.get('input[type=text]').type('fakemail@fake.com')
    cy.get('input[type=text]').should('have.value', 'fakemail@fake.com')
    cy.get('input[type=password]').type('password')
    cy.get('input[type=password]').should('have.value', 'password')
    cy.get('button').click()
  })
  it('Input Valid Username and Password', () => {
    cy.visit('http://localhost:4200/login')
    cy.url().should('include', '/login')
    cy.get('input[type=text]').type('d2')
    cy.get('input[type=text]').should('have.value', 'd2')
    cy.get('input[type=password]').type('d2')
    cy.get('input[type=password]').should('have.value', 'd2')
    cy.get('button').click()
  })
})